name: Check for Duplicates in Quotes File

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - 'public/quotes.txt'

jobs:
  check-duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for duplicate lines in quotes.txt
        run: |
          if [ -f public/quotes.txt ]; then
            echo -e "\033[1;34mAnalyzing public/quotes.txt for duplicates...\033[0m"
            duplicates=$(sort public/quotes.txt | uniq -d)
            if [ -n "$duplicates" ]; then
              echo -e "\033[1;31mDuplicate lines found in public/quotes.txt.\033[0m"
              echo -e "\033[1;33mSummary of duplicates:\033[0m"
              echo "$duplicates"
              echo
              echo -e "\033[1;36mDetails of duplicate lines with line numbers and occurrences:\033[0m"
              awk '{count[$0]++; lines[$0]=lines[$0] ? lines[$0]", "NR : NR} END {for (line in count) if (count[line] > 1) printf "\033[1;31m%d occurrences\033[0m: Line(s) \033[1;33m%s\033[0m -> \033[1;36m%s\033[0m\n", count[line], lines[line], line}' public/quotes.txt | sort -u
              exit 1
            else
              echo -e "\033[1;32mNo duplicate lines found in public/quotes.txt.\033[0m"
            fi
          else
            echo -e "\033[1;33mFile public/quotes.txt not found. Skipping check.\033[0m"
          fi
