name: Code Quality and Build Check

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: |
          bun run eslint .
          if [ $? -ne 0 ]; then
            echo "Linting issues detected. Please fix them before proceeding."
            exit 1
          fi

      - name: Run build
        run: |
          bun run build
