name: Check Quotes

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - 'public/quotes.txt'

jobs:
  check-duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for duplicate lines in quotes.txt
        run: |
          if [ -f public/quotes.txt ]; then
            echo -e "\033[1;34mAnalyzing public/quotes.txt for duplicates...\033[0m"
            duplicates=$(sort public/quotes.txt | uniq -d)
            if [ -n "$duplicates" ]; then
              echo -e "\033[1;31mDuplicate lines found in public/quotes.txt.\033[0m"
              echo -e "\033[1;33mSummary of duplicates:\033[0m"
              echo "$duplicates"
              echo
              echo -e "\033[1;36mDetails of duplicate lines with line numbers and occurrences:\033[0m"
              awk '{count[$0]++; lines[$0]=lines[$0] ? lines[$0]", "NR : NR} END {for (line in count) if (count[line] > 1) printf "\033[1;31m%d occurrences\033[0m: Line(s) \033[1;33m%s\033[0m -> \033[1;36m%s\033[0m\n", count[line], lines[line], line}' public/quotes.txt | sort -u
              exit 1
            else
              echo -e "\033[1;32mNo duplicate lines found in public/quotes.txt.\033[0m"
            fi
          else
            echo -e "\033[1;33mFile public/quotes.txt not found. Skipping check.\033[0m"
          fi

      - name: Check for whitespace issues in quotes.txt
        run: |
          if [ -f public/quotes.txt ]; then
            echo -e "\033[1;34mAnalyzing public/quotes.txt for whitespace issues...\033[0m"
      
            # Search for leading or trailing whitespace
            whitespace_issues=$(grep -En "^[[:space:]]+|[[:space:]]+$" public/quotes.txt)
            if [ -n "$whitespace_issues" ]; then
              echo -e "\033[1;31mWhitespace issues found in public/quotes.txt.\033[0m"
              echo -e "\033[1;33mLines with leading or trailing whitespace:\033[0m"
              echo "$whitespace_issues" | while IFS= read -r line; do
                line_number=$(echo "$line" | cut -d: -f1)
                content=$(echo "$line" | cut -d: -f2-)
                # Highlight leading and trailing whitespace in red background
                highlighted_content=$(echo "$content" | sed -E $'s/^([[:space:]]+)/\033[1;41m\\1\033[0m/; s/([[:space:]]+)$/\033[1;41m\\1\033[0m/')
                # Properly output highlighted line
                echo -e "\033[1;31mLine $line_number:\033[0m \"$highlighted_content\""
              done
              exit 1
            else
              echo -e "\033[1;32mNo whitespace issues found in public/quotes.txt.\033[0m"
            fi
          else
            echo -e "\033[1;33mFile public/quotes.txt not found. Skipping check.\033[0m"
          fi
          
